package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"

	"github.com/elisalimli/meetmeup/common"
	"github.com/elisalimli/meetmeup/graphql/models"
)

// UserCreate is the resolver for the userCreate field.
func (r *mutationResolver) UserCreate(ctx context.Context, user models.UserInput) (*models.User, error) {
	context := common.GetContext(ctx)
	usr := models.User{
		Email:     user.Email,
		FirstName: user.FirstName,
		LastName:  user.LastName,
	}

	context.Database.Create(&usr)
	return &usr, nil
}
