package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"
	"fmt"

	"github.com/elisalimli/meetmeup/graph/generated"
	"github.com/elisalimli/meetmeup/models"
)

// TodoCreate is the resolver for the todoCreate field.
func (r *mutationResolver) TodoCreate(ctx context.Context, todo models.TodoInput) (*models.Todo, error) {
	panic(fmt.Errorf("not implemented: TodoCreate - todoCreate"))
}

// TodoComplete is the resolver for the todoComplete field.
func (r *mutationResolver) TodoComplete(ctx context.Context, id int, updatedBy int) (*models.Todo, error) {
	panic(fmt.Errorf("not implemented: TodoComplete - todoComplete"))
}

// TodoDelete is the resolver for the todoDelete field.
func (r *mutationResolver) TodoDelete(ctx context.Context, id int, updatedBy int) (*models.Todo, error) {
	panic(fmt.Errorf("not implemented: TodoDelete - todoDelete"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
