// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type FieldError struct {
	Path    string `json:"path"`
	Message string `json:"message"`
}

type ResponseTodoCreate struct {
	Errors []*FieldError `json:"errors"`
	Todo   *Todo         `json:"todo"`
}
